# Generated by Django 3.2.6 on 2021-08-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shivam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('minskills', models.CharField(max_length=140)),
                ('phone_number', models.CharField(max_length=120)),
            ],
        ),
    ]
