# Generated by Django 3.2.6 on 2021-09-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grocery_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('status', models.CharField(max_length=140)),
                ('amount', models.CharField(max_length=120)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='shivam',
        ),
    ]
