# Generated by Django 3.2.6 on 2021-09-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210902_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery_item',
            name='user_name',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
